
apiVersion: v1
kind: Service
metadata:
  name: say-service
  labels:
    app: say
spec:
  ports:
  - port: 8080
    name: set
  clusterIP: None
  selector:
    app: say
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: say-statefulset
  labels:
    app: say
spec:
  selector:
    matchLabels:
      app: say # has to match .spec.template.metadata.labels
  serviceName: "set"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: say # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: say
        image: gcr.io/text2speech-190611/say
        ports:
        - containerPort: 8080
          name: set
---

kind: Service
apiVersion: v1
metadata:
  name: say-service-lb
spec:
  selector:
    app: say
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
